### PR TITLE
Fixed build processing in arrow search

### PR DESCRIPTION
**Pull request by a-gubskiy**
This is old changes by @novosaleks 
@niravzi  please check if it is still actual.

### CODE REVIEW

**Comment by niravzi** [comment]
@a-gubskiy looks outdated. Current code is in somewhat similar state but with a small differences.

**Comment by niravzi** [comment]
Yeah it has conflicts.

**Comment by a-gubskiy** [comment]
@niravzi can we close it?

**Comment by niravzi** [comment]
@a-gubskiy yes.

**Pull request closed without merging**
